### ISSUE TITLE
One of the variant lines is malformed string at stdout when parsing vcf files with no variants

### ISSUE THREAD

**Issue by kulvait** [moonso/vcf_parser#16]
If I use vcfparser like this
`vcf_parser empty.vcf --split > output.vcf`

where empty.vcf is vcf file with no variants in it (only header) then to the end of the output.vcf is inserted string
**One of the variant lines is malformed:**
Please fix that since I am using it in my pipeline and the output.vcf is in incorrect format.

Thanks,
Vojtech.

**Comment by kulvait** [comment]
Thank you!

**Comment by moonso** [comment]
👍
