### ISSUE TITLE
simplying multiallelic representation after split

### ISSUE THREAD

**Issue by ycl6** [moonso/vcf_parser#19]
Using the `--split` function split multiallelic representation into multiple lines. However, can `vcf_parser` further process the `REF` and `ALT` fields so that redundant nucleotides were removed from both fields.

For example, the original VCF has the following call
```
1       19566296        rs2273046       TGTTGCCTGCA     CGTTGCCTGCA,T   87098835.74     PASS
```

`vcf_parser --split` generate the split representation
```
1       19566296        rs2273046       TGTTGCCTGCA     CGTTGCCTGCA     8.709883574E7   PASS
1       19566296        rs2273046       TGTTGCCTGCA     T       8.709883574E7   PASS
```

The desired output
```
1       19566296        rs2273046       T     C     8.709883574E7   PASS
1       19566296        rs2273046       TGTTGCCTGCA     T       8.709883574E7   PASS
```

**Comment by moonso** [comment]
Hi,

vcf_parser will not normalize, there are excellent tools that have solved this problem and does it very fast. Please check out [vt](http://genome.sph.umich.edu/wiki/Vt#Normalization) or [bcf tools](https://github.com/samtools/bcftools).

Good luck!
