### ISSUE TITLE
Getting "VCF files allways [sic] have to start with a metadata line." File appears to be correctly formatted.

### ISSUE THREAD

**Issue by cogburnd02** [moonso/vcf_parser#20]
The file begins like so:

    BEGIN:VCARD
    VERSION:3.0
    PRODID:-Apple Inc.//iPhone OS 15.6.1//EN

It has CR/LF (DOS-style) line-endings. This appears to be adherent to the [RFC 6350](https://datatracker.ietf.org/doc/html/rfc6350) spec for vCard.

What is going on here?

I'd like to use this to parse vCard files I get on my phone (texted from my mom (I use Android, not IOS)) using termux.

(Also, always is spelled with only one 'ell')

**Comment by moonso** [comment]
Hi, unfortunately this project has nothing to do with VCARD files but rather Variant Call Format Files (VCF) that is used to describe genomic variations. 

Thank you for the spell check.
