### ISSUE TITLE
importing vcf_parser screws up readline

### ISSUE THREAD

**Issue by kghose** [moonso/vcf_parser#3]
When in the ipython environment executing

`from vcf_parser import VCFParser`

leads to some weird state for readline, causing autocompletion and cursor keys to screw up in ipython.

**Comment by moonso** [comment]
Hello, I just tried this and it works in my environment:

```python
(testing)130-229-5-42-dhcp:vcf_parser manmag$ ipython
Python 2.7.6 (default, May 17 2014, 17:10:40)
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from vcf_parser import VCFParser

In [2]: VCFParser?
Type:            type
String form:     <class 'vcf_parser.parser.VCFParser'>
File:            /Users/manmag/Projects/vcf_parser/vcf_parser/parser.py
Init definition: VCFParser(self, infile=None, fsock=None, split_variants=False)
Docstring:       docstring for VCFParser

In [3]: my_parser = VCFParser(infile='examples/test_vcf.vcf')
```
can you post your session?

**Comment by moonso** [comment]
Or maybe I don't understand the problem?

**Comment by moonso** [comment]
Ok I understand what you meant.
The parser was changing the stdout writer but that messed up ipython.
I've updated this in version 1.1.5 so please update and try again...

**Comment by kghose** [comment]
Hi,

Thanks for your quick response.

Basically things to do with cursor navigation and special keys are screwing
up. So normally ipython will do tab-completion for you. ipython will let
you use cursor keys to move around in the command line, but these are
broken after importing.

If you need further clarification I will try a screen cast.

Best
-Kaushik

**Comment by kghose** [comment]
Ah, sweet. Seems to be working now. Thanks again. Best -Kaushik
