### ISSUE TITLE
pypi version 1.2 differ from github version 1.2

### ISSUE THREAD

**Issue by dakl** [moonso/vcf_parser#7]
Hi Måns, 

It seems that the version which is fetched from pypi when installed using pip doesn't contain the latest fixes, even though it is labelled as 1.2, which afaik is the same as on github. Specifically, line 561 of parser.py (on pypi) is

```
variant['FORMAT'] = gt_format
```

but on github, it's changed to the block

```
if 'FORMAT' in variant_dict:
  gt_format = variant_dict['FORMAT']
  variant['FORMAT'] = gt_format
```

cheers

**Comment by moonso** [comment]
Sorry about that. Fixed in 1.2.1:)
