### ISSUE TITLE
How to represent reference allele in gt calls when splitting multiple alternative alleles

### ISSUE THREAD

**Issue by moonso** [moonso/vcf_parser#8]
@dakl we discussed this earlier and you proposed that, for example

    1/2

should be represented by

    ./1 and ./1

I agree that the current representation that looks like

    0/1 and 0/1

is not correct since we have not seen the reference allele anywhere.
The problem with the new way of annotating is that one can interpret the call as:
"we do not know what is on the other allele".
But this is, in my opinion, also wrong.
So the question is, what is most informative?

**Comment by moonso** [comment]
One way would be to let the user specify the representation via a flag on the command line.

**Comment by dakl** [comment]
From the VCFv4.2 spec:

```
If a call cannot be made for a sample at a given locus, ‘.’ should be specified for each missing allele in the GT field
```

So the `.` really just means that a call cannot be made from the available REF and ALT alleles in the given record, not that it's not known. It can technically be known, just elsewhere. I think my current standpoint is that `./1` is technically correct, backed by the spec. 

One possible solution would be to have a different character than `.` to indicate "called, but listed elsewhere" for multiallelic variants. Maybe `M/1` /  `M/1` could be used for this. This would likely break many downstream tools which expect . or a number. This has to be supported by spec, of course. 

If you have time, I suggest posting this on the hts-specs issue tracker (https://github.com/samtools/hts-specs/issues), it would be interesting to see their view on this. Their issues are discussed at quarterly telcos, so we shouldn't expect rapid turnaround though.

**Comment by moonso** [comment]
https://github.com/samtools/hts-specs/issues/77 <https://github.com/samtools/hts-specs/issues/77>

:)

**Comment by moonso** [comment]
In version 1.3 you can choose symbol for representing an unobserved allele with 
```--allele_symbol .```
